# Generated by Django 4.2 on 2023-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
